# https://docs.flutter.dev/get-started/install/linux#additional-linux-requirements
- name: linux dependencies
  ansible.builtin.apt:
    pkg:
    - clang
    - cmake
    - ninja-build
    - pkg-config
    - libgtk-3-dev
    - liblzma-dev
  become: true

- include_tasks: "common/{{ubuntu_default}}/main.yml"

# Do: automate this with Python!
- include_tasks: "common/sign licenses/main.yml"