# https://docs.flutter.dev/get-started/install/linux#get-sdk

- name: Install Flutter using snapd
  community.general.snap:
    name:
      - flutter
    classic: true
  become: true
  notify: initialize Flutter Snap