- name: gitignore ansible.cfg
  ansible.builtin.lineinfile:
    path: "{{role_path}}/.gitignore"
    regexp: "^ansible.cfg"
    line: "ansible.cfg"
    create: true

- name: build ansible.cfg
  ansible.builtin.blockinfile:
    path: "{{role_path}}/ansible.cfg"
    create: true
    block: |
      Match User ansible-agent
      PasswordAuthentication no
      [defaults]
      inventory = {{dynamic_inventory}}
      roles_path = {{role_dir}}

- name: link ansible.cfg
  ansible.builtin.file:
    src: "{{role_dir}}/ansible.cfg"
    dest: "{{playbook_dir}}/ansible.cfg"
    state: link
