- name: gitignore dependency
  ansible.builtin.lineinfile:
    path: "{{role_path}}/.gitignore"
    regexp: "^{{item}}"
    line: "{{item}}"
    create: true
  loop:
  - "{{depend}}"
  - "{{role_folder}}"

- name: Git checkout
  ansible.builtin.git:
    repo: "{{item.repo}}"
    dest: "{{item.subdir}}/{{item.name}}"
    update: false
  loop: "{{repo}}"

- name: Link dependency roles
  ansible.builtin.file:
    src: "{{depend_dir}}/{{item.name}}/{{item.path}}"
    dest: "{{role_dir}}/{{item.name}}"
    state: link
  loop: "{{role}}"

# - name: Link dependency roles
#   debug:
#     msg: "src: {{depend_dir}}/{{item.name}}/{{item.path}} dest: {{role_dir}}/{{item.name}}"
#   loop: "{{role}}"
