- name: gitignore dependencies
  ansible.builtin.lineinfile:
    path: "{{role_path}}/.gitignore"
    regexp: "^{{item}}"
    line: "{{item}}"
    create: true
  loop:
  - "{{depend}}"
  - "{{roles}}"

- name: Git checkout
  ansible.builtin.git:
    repo: "{{item.repo}}"
    dest: "{{item.subdir}}{{item.name}}"
    update: false
  loop: "{{repo}}"

- name: Link dependency roles
  ansible.builtin.file:
    src: "{{item.path}}"
    dest: "{{role_path}}/.roles/{{item.name}}"
    state: link
  loop: "{{roles}}"
