- name: gitignore dependencies
  ansible.builtin.lineinfile:
    path: "{{role_path}}/.gitignore"
    regexp: "^.pre/{{depends}}"
    line: ".pre/{{depend}}"
    create: true

- name: Git checkout
  ansible.builtin.git:
    repo: "{{item.repo}}"
    dest: "{{item.subdir}}{{item.name}}"
    update: false
  loop: "{{repo}}"

- debug:
    msg: "{{role_path}}, {{playbook_dir}}"