- name: run `flutter doctor` to Debug problems
  block:
  - name: run test
    ansible.builtin.shell: flutter doctor >> flutter.test
    args:
      chdir: "{{output}}"

  - name: view
    ansible.builtin.shell: "xdg-open {{output}}/flutter.test"
  when: debug