---
- hosts: localhost
  roles:
  - .pre

- hosts: localhost
  vars:
    editor: android studio
    # Host_vars
    ansible_become_password: u
    ansible_user: "{{lookup('ansible.builtin.env', 'USER')}}"

  roles:
  - Flutter
  - editor plugin